media:
  input: public/uploads
  output: /uploads

content:
  - name: menu
    label: Menu
    type: file
    path: src/content/menu/menu.md
    fields:
      - name: body
        label: Menu Content
        type: markdown

  - name: testimonials
    label: Testimonials
    type: collection
    path: src/content/testimonials
    fields:
      - name: author
        label: Author
        type: string
        required: true
      - name: isFeatured
        label: Featured on Homepage
        type: boolean
      - name: quote
        label: Quote
        type: text

  - name: gallery
    label: Gallery
    type: collection
    path: src/content/gallery
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: image
        label: Image
        type: image
      - name: order
        label: Display Order
        type: number
